// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDependencies() {
  return window['go']['main']['App']['CheckDependencies']();
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DetectPlatform(arg1) {
  return window['go']['main']['App']['DetectPlatform'](arg1);
}

export function DownloadTask(arg1) {
  return window['go']['main']['App']['DownloadTask'](arg1);
}

export function GetAllTasks() {
  return window['go']['main']['App']['GetAllTasks']();
}

export function GetDebugInfo() {
  return window['go']['main']['App']['GetDebugInfo']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function GetTaskSubtitles(arg1) {
  return window['go']['main']['App']['GetTaskSubtitles'](arg1);
}

export function ListActiveTasks() {
  return window['go']['main']['App']['ListActiveTasks']();
}

export function ParseVideoUrl(arg1) {
  return window['go']['main']['App']['ParseVideoUrl'](arg1);
}

export function RetryTask(arg1) {
  return window['go']['main']['App']['RetryTask'](arg1);
}

export function StartTranscription(arg1, arg2) {
  return window['go']['main']['App']['StartTranscription'](arg1, arg2);
}

export function SummarizeTask(arg1) {
  return window['go']['main']['App']['SummarizeTask'](arg1);
}

export function TranscribeTask(arg1) {
  return window['go']['main']['App']['TranscribeTask'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateTaskSourceLanguage(arg1, arg2) {
  return window['go']['main']['App']['UpdateTaskSourceLanguage'](arg1, arg2);
}
