// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDependencies() {
  return window['go']['main']['App']['CheckDependencies']();
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetAllTasks() {
  return window['go']['main']['App']['GetAllTasks']();
}

export function GetCurrentTask() {
  return window['go']['main']['App']['GetCurrentTask']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTaskSubtitles(arg1) {
  return window['go']['main']['App']['GetTaskSubtitles'](arg1);
}

export function ParseVideoUrl(arg1) {
  return window['go']['main']['App']['ParseVideoUrl'](arg1);
}

export function RetryTask(arg1) {
  return window['go']['main']['App']['RetryTask'](arg1);
}

export function StartTranscription(arg1, arg2) {
  return window['go']['main']['App']['StartTranscription'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
