// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {main} from '../models';

export function CheckDependencies():Promise<types.DependencyStatus>;

export function DeleteTask(arg1:string):Promise<void>;

export function DetectPlatform(arg1:string):Promise<string>;

export function DownloadTask(arg1:string):Promise<types.Task>;

export function GetAllTasks():Promise<Array<types.Task>>;

export function GetDebugInfo():Promise<Record<string, string>>;

export function GetSettings():Promise<types.Settings>;

export function GetTask(arg1:string):Promise<types.Task>;

export function GetTaskSubtitles(arg1:string):Promise<Array<main.SubtitleEntry>>;

export function ListActiveTasks():Promise<Array<types.Task>>;

export function ParseVideoUrl(arg1:string):Promise<types.VideoMetadata>;

export function RetryTask(arg1:string):Promise<types.Task>;

export function StartTranscription(arg1:string,arg2:string):Promise<types.Task>;

export function SummarizeTask(arg1:string):Promise<types.Task>;

export function TranscribeTask(arg1:string):Promise<types.Task>;

export function UpdateSettings(arg1:types.Settings):Promise<types.Settings>;

export function UpdateTaskSourceLanguage(arg1:string,arg2:string):Promise<types.Task>;
